### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by UtkarshA135** [piyush97/highest#3]
Hi bro, I'm not able to login actually!
I tried signing up with Google Github both doesn't work.
Please have a look.
![IMG_20220515_105206](https://user-images.githubusercontent.com/62795322/168458429-3a91d21f-d656-4880-9680-72d56bf21117.jpg)

**Comment by piyush97** [comment]
> Hi bro, I'm not able to login actually!
> 
> I tried signing up with Google Github both doesn't work.
> 
> Please have a look.
> 
> ![IMG_20220515_105206](https://user-images.githubusercontent.com/62795322/168458429-3a91d21f-d656-4880-9680-72d56bf21117.jpg)
> 
> 

Hey, thanks for showing interest. Currently, I've kept the app to be invite only. 

Thanks

**Comment by UtkarshA135** [comment]
Ok nice work though 🔥🚀
